name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    name: "Test Linux"
    runs-on: ubuntu-latest
    container: swift:5.10-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Swift PM
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}-v4
          restore-keys: ${{ runner.os }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --parallel --sanitize=thread
